project:
  type: website
  output-dir: _site

website:
  title: "Lancelot Da Costa"
  navbar:
    title: "Lancelot Da Costa"
    logo-href: "https://www.lancelotdacosta.com/"
    left: []
    right: []

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    math: mathjax
    page-layout: full
    grid:
      body-width: 210mm
      margin-width: 0px
