project:
  type: website
  output-dir: _site

website:
  title: "Lancelot Dacosta — Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    math: mathjax

